#!/usr/bin/env sh
set -eu
root="$(git rev-parse --show-toplevel)"
cd "$root"
dotnet restore --locked-mode
dotnet format --verify-no-changes --no-restore
dotnet build --no-restore -warnaserror
dotnet test --no-build
