<#
.SYNOPSIS
    Compares a generated project's recorded starter-kit version against the catalogue's current
    VERSION and prints proposed upgrade notes. Read-only: never modifies the generated project.

.DESCRIPTION
    Reads <ProjectPath>/.ai/generation.json for `starterKitVersion` and `profile`, compares it to
    this catalogue's VERSION file, and prints the change level (major/minor/patch), the profile's
    current verification baseline from manifests/profiles.json, and the general migration steps
    documented in docs/upgrades/migration-guide.md.

.PARAMETER ProjectPath
    Path to a project previously generated by scripts/create-project.ps1.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ProjectPath
)

$ErrorActionPreference = "Stop"
$catalogRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path

$projectRoot = (Resolve-Path -LiteralPath $ProjectPath).Path
$generationRecordPath = Join-Path $projectRoot ".ai\generation.json"
if (-not (Test-Path -LiteralPath $generationRecordPath)) {
    throw "Not a generated project: .ai/generation.json is missing at $generationRecordPath"
}
$record = Get-Content -LiteralPath $generationRecordPath -Raw | ConvertFrom-Json

$catalogVersionPath = Join-Path $catalogRoot "VERSION"
if (-not (Test-Path -LiteralPath $catalogVersionPath)) {
    throw "Catalogue VERSION file is missing: $catalogVersionPath"
}
$catalogVersion = (Get-Content -LiteralPath $catalogVersionPath -Raw).Trim()

$projectVersion = [string]$record.starterKitVersion
$profileName = [string]$record.profile

function ConvertTo-VersionParts {
    param([Parameter(Mandatory = $true)][string]$Value)
    $parts = $Value.Split('.')
    [pscustomobject]@{
        Major = [int]($parts[0])
        Minor = if ($parts.Count -gt 1) { [int]$parts[1] } else { 0 }
        Patch = if ($parts.Count -gt 2) { [int]$parts[2] } else { 0 }
    }
}

Write-Output "Project:                   $($record.projectName)"
Write-Output "Profile:                   $profileName"
Write-Output "Generated at (UTC):        $($record.generatedAtUtc)"
Write-Output "Project starterKitVersion: $projectVersion"
Write-Output "Catalogue current VERSION: $catalogVersion"
Write-Output ""

if ($projectVersion -eq $catalogVersion) {
    Write-Output "Up to date: no starter-kit version delta detected. No action required."
    exit 0
}

$projectVer = ConvertTo-VersionParts -Value $projectVersion
$catalogVer = ConvertTo-VersionParts -Value $catalogVersion

$changeLevel = if ($catalogVer.Major -ne $projectVer.Major) {
    "major"
} elseif ($catalogVer.Minor -ne $projectVer.Minor) {
    "minor"
} else {
    "patch"
}

Write-Output "Change level since generation: $changeLevel"
Write-Output ""

$manifestPath = Join-Path $catalogRoot "manifests\profiles.json"
if (Test-Path -LiteralPath $manifestPath) {
    $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
    $profileConfig = $manifest.profiles.PSObject.Properties[$profileName]
    if ($null -ne $profileConfig) {
        Write-Output "Current verification baseline for '$profileName':"
        Write-Output "  $($profileConfig.Value.verification)"
        Write-Output ""
        Write-Output "Current recommended skills for '$profileName':"
        foreach ($skill in $profileConfig.Value.recommendedSkills) {
            $installed = Test-Path -LiteralPath (Join-Path $projectRoot "skills\$skill")
            $marker = if ($installed) { "[installed]" } else { "[missing]" }
            Write-Output "  - $skill $marker"
        }
        Write-Output ""
    }
}

Write-Output "Recommended next steps (see docs/upgrades/migration-guide.md for full detail):"
Write-Output "  1. Diff AGENTS.md, .ai/*.md, hooks/, and .github/workflows/ against templates/$profileName"
Write-Output "     and the catalogue root; preserve this project's product-specific edits."
Write-Output "  2. Pull forward any missing skills listed above that are relevant to this project."
Write-Output "  3. Regenerate lock files as needed (uv.lock / packages.lock.json) before re-verifying."
Write-Output "  4. Re-run the verification baseline printed above."
Write-Output "  5. Once verified, update .ai/generation.json starterKitVersion to '$catalogVersion'."
Write-Output "  6. A human must review, stage, commit, and push the migration."
Write-Output ""
Write-Output "This assessment is read-only; it did not modify $projectRoot."
