#!/usr/bin/env sh
set -eu
root="$(git rev-parse --show-toplevel)"
cd "$root"
if [ -x ./mvnw ]; then
  ./mvnw -q spotless:check checkstyle:check pmd:check spotbugs:check test
else
  mvn -q spotless:check checkstyle:check pmd:check spotbugs:check test
fi
