#!/usr/bin/env sh
set -eu
dotnet restore --use-lock-file
dotnet build --no-restore -warnaserror
dotnet test --no-build --collect:"XPlat Code Coverage" --settings coverlet.runsettings
dotnet list package --vulnerable --include-transitive
